ANPdata:
- creation_date = "2021/8/3"
- maturity = "production"
- updated_date = "2021/8/3"
ANPrule:
- author: ["Elastic"]

- description: "Identifies use of bcdedit.exe to delete boot configuration data. This tactic is sometimes used as by malware or an attacker as a destructive technique."

- language: "eql"

- license: "Elastic License v2"

- risk_score: 21

- rule_id: "69c251fb-a5d6-4035-b5ec-40438bd829ff"

- severity: "low"

- tags: ["Elastic", "Host", "Windows", "Threat Detection", "Defense Evasion"]

- type: "eql"

- threat: [

    [framework : "MITRE ATT&CK",
      technique: [
        id : "T1070",
        name : "Indicator Removal on Host",
        reference : "https://attack.mitre.org/techniques/T1070/",
        subtechnique: [
          [id : "T1070.004",        
          name : "File Deletion",        
          reference : "https://attack.mitre.org/techniques/T1218/004/"]
        ]
      ],
      tactic: [
        id : "TA0005",
        name : "Defense Evasion",
        reference : "https://attack.mitre.org/tactics/TA0005/"]]]
      
name: "Modification of Boot Configuration"
index: anp-log-agentbase-winclient
type: any
eql:
  "query": "process where event.type in (\"start\", \"process_started\") and
    (process.name : \"bcdedit.exe\" or process.pe.original_file_name == \"bcdedit.exe\") and
    (process.args : \"/set\" and process.args : \"bootstatuspolicy\" and process.args : \"ignoreallfailures\") or
    (process.args : \"no\" and process.args : \"recoveryenabled\")"
  
alert:
- "slack"

slack:
slack_webhook_url: "https://hooks.slack.com/services/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"
