ANPdata:
- creation_date = "2021/8/11"
- maturity = "production"
# - query_schema_validation = false
- updated_date = "2021/8/11"
# - min_stack_version = "7.12.0"
ANPrule:
- author: ["Elastic"]

- description: "Identifies a privilege escalation attempt via a rogue Windows directory (Windir) environment variable. This is a known
    primitive that is often combined with other vulnerabilities to elevate privileges."

# - false_positives:  ["""Uninstall or manual deletion of a legitimate printing driver files. Verify the printer file metadata such as
    # manufacturer and signature information."""]

# - interval: "60m"

- language: "eql"

- license: "Elastic License v2"

- note: "## Threat intel Refer to CVEs, CVE-2020-1048 and CVE-2020-1337 for further information on the vulnerability and exploit. Verify that the relevant system is patched."

- references: ["https://www.tiraniddo.dev/2017/05/exploiting-environment-variables-in.html"]

# - max_signals: 33

- risk_score: 73

- rule_id: "d563aaba-2e72-462b-8658-3e5ea22db3a6"

- severity: "high"

- tags: ["Elastic", "Host", "Windows", "Threat Detection", "Privilege Escalation"]

- type: "eql"

- threat: [

    [framework : "MITRE ATT&CK",
      technique: [
        id : "T1574",
        name : "Hijack Execution Flow",
        reference : "https://attack.mitre.org/techniques/T1574/",
        subtechnique: [
          [id : "T1574.007",        
          name : "Path Interception by PATH Environment Variable",        
          reference : "https://attack.mitre.org/techniques/T1574/007/"]
        ]
      ],
      tactic: [
        id : "TA0004",
        name : "Privilege Escalation",
        reference : "https://attack.mitre.org/tactics/TA0004/"]]
  ]

name: "Privilege Escalation via Windir Environment Variable"
index: anp-log-agentbase-winclient
type: any
eql:
  "query": "registry where registry.path : (\"HKEY_USERS\\\\*\\\\Environment\\\\windir\", \"HKEY_USERS\\\\*\\\\Environment\\\\systemroot\") and not registry.data.strings : (\"C:\\\\windows\", \"%SystemRoot%\")"

  
alert:
- "slack"

slack:
slack_webhook_url: "https://hooks.slack.com/services/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"
