ANPdata:
- creation_date = "2021/08/08"
- maturity = "production"
- updated_date = "2021/08/08"

ANPrule:
- author = ["Elastic"]

- description = """Adversaries may dump the content of the keychain storage data from a system to acquire credentials. Keychains are the
    built-in way for macOS to keep track of users' passwords and credentials for many services and features, including Wi-Fi
    and website passwords, secure notes, certificates, and Kerberos."""

- language = "eql"

- license = "Elastic License v2"

- references = ["https://ss64.com/osx/security.html"]

- risk_score = 73

- rule_id =  "565d6ca5-75ba-4c82-9b13-add25353471c"

- severity = "high"

- tags =  ["Elastic", "Host", "macOS", "Threat Detection", "Credential Access"]

- type = "eql"

name: "Dumping of Keychain Content via Security Command"

index: ["auditbeat-*", "logs-endpoint.events.*"]

type: any

eql:
  "query": "process where event.type in (\"start\", \"process_started\") and process.args : \"dump-keychain\" and process.args : \"-d\""

threat:
  - 01:
    - threat_rule: 
      - framework = "MITRE ATT&CK"
    - technique:
      - id = "T1555"
      - name = "Credentials from Password Stores"
      - reference = "https://attack.mitre.org/techniques/T1555/"
      - subtechnique:
        - id = "T1555.001"
        - name = "Keychain"
        - reference = "https://attack.mitre.org/techniques/T1555/001/"
    - tactic:
      - id = "TA0006"
      - name =  "Credential Access"
      - reference = "https://attack.mitre.org/tactics/TA0006/"

alert:
- "slack"

slack:
slack_webhook_url: "https://hooks.slack.com/services/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"
