# Generated by Django 3.2 on 2022-01-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='sequence',
        ),
    ]
