# Generated by Django 3.2 on 2022-01-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_remove_config_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='sequence',
            field=models.BooleanField(default=False),
        ),
    ]
